# Generated by Django 3.0.7 on 2020-06-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Features')),
                ('description', models.CharField(max_length=512, verbose_name='Features Description')),
                ('number', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
