# Generated by Django 3.0.7 on 2020-06-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Renter'), (2, 'Agent'), (3, 'Admin')], default=1, null=True),
        ),
    ]
