# Generated by Django 3.0.7 on 2020-06-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0001_initial'),
        ('Accounts', '0002_auto_20200628_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renter_property_pref',
            name='suburb',
        ),
        migrations.AddField(
            model_name='renter_property_pref',
            name='suburb',
            field=models.ManyToManyField(blank=True, related_name='Renter_Suburb_Wants', to='Location.Location'),
        ),
    ]
