# Generated by Django 3.0.7 on 2020-06-26 14:59

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Accounts', '0001_initial'),
        ('RentDayProvider', '0001_initial'),
        ('Location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Property Name')),
                ('description',
                 models.TextField(blank=True, max_length=512, null=True, verbose_name='Property Description')),
                ('bathrooms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of bathroom')),
                ('bedrooms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of bedroom')),
                ('kitchen', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of kitchen')),
                ('living_area',
                 models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Number of LivingArea')),
                ('rent', models.PositiveIntegerField(blank=True, null=True, verbose_name='Property Rent')),
                ('parking_spot', models.PositiveSmallIntegerField(blank=True,
                                                                  choices=[(1, 'Street Parking'), (2, 'Garage Parking'),
                                                                           (3, 'Undercover Parking')], null=True,
                                                                  verbose_name='Parking Spot Type')),
                ('parking_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('land_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Size of land')),
                ('indoor_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Size of indoor')),
                ('lease_length', models.PositiveIntegerField(blank=True, null=True)),
                ('date_available', models.DateField(blank=True, null=True)),
                ('property_type',
                 models.PositiveSmallIntegerField(choices=[(1, 'Apartment'), (2, 'House'), (3, 'Room')], null=True)),
                ('walkthrough',
                 models.FileField(blank=True, null=True, upload_to='', verbose_name='Property walkthrough')),
                (
                    'floor_plan',
                    models.FileField(blank=True, null=True, upload_to='', verbose_name='Property FloorPlan')),
                (
                    'posted',
                    models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Posted On')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                            related_name='agent_of_property', to=settings.AUTH_USER_MODEL,
                                            verbose_name='Property Agent')),
                ('features',
                 models.ManyToManyField(blank=True, related_name='Property_Feature', to='RentDayProvider.Feature')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                               to='Location.Location')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                            related_name='owner_of_property', to='Accounts.Owner',
                                            verbose_name='Property Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Property_Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=64)),
                ('video', models.FileField(upload_to='')),
                ('property',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_video',
                                   to='Property.Property', verbose_name='Image of property')),
            ],
        ),
        migrations.CreateModel(
            name='Property_Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(blank=True, max_length=64)),
                ('image', models.ImageField(upload_to='')),
                ('image_type',
                 models.IntegerField(choices=[(1, 'Interior'), (2, 'Exterior')], verbose_name='Property Image Type')),
                ('property',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_image',
                                   to='Property.Property', verbose_name='Image of property')),
            ],
        ),
    ]
